name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
            target/
          key: wasm32-unknown-unknown-nightly
          restore-keys: |
            wasm32-unknown-unknown-nightly
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true
      - name: Build wasm
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target wasm32-unknown-unknown
      - name: Create dist folder
        run: |
          rm -rf dist
          mkdir -p dist
      - name: Get bind wasm
        uses: jetli/wasm-bindgen-action@v0.1.0
        with:
          version: '0.2.79'
      - name: Bind wasm
        run: wasm-bindgen --out-dir ./dist --target web ./target/wasm32-unknown-unknown/release/puzzle.wasm
      - name: Make public
        run: |
          cp ./index.html ./dist/
          cp -R ./assets ./dist/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
